spring:
  application:
    name: huertohogar-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://ep-plain-cell-acpt0m8o-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_MdaHJtnu7x6v
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.huertohogar: DEBUG

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-expiration: 604800000

transbank:
  webpay:
    environment: TEST
    commerce-code: 597055555532
    api-key: 579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
    return-url: http://localhost:3000/payment-result

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600